#公共配置
server:
  port: 10010
  tomcat:
    uri-encoding: UTF-8


logging:
  config: classpath:log/logback.xml
  path: C:\\Users\\Administrator\\Desktop\\test\\logs
#  path: /data/logs/wave-apartment/user-service
  level:
    com:
      wave:
        carRecord:
          dao: debug
#            carGate: debug
spring:
  application:
    name: car-record
  devtools:
    restart:
      enabled: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


  # 数据源配置
  datasource:
    cargate:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://10.0.10.199:3336/BUS?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: pig
      password: uts08965421021!

    uts:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://10.0.10.199:3336/crscell?characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      username: pig
      password: uts08965421021!
    
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 配置测试查询语句
      validationQuery: SELECT 1 FROM DUAL
      # 初始化大小，最小，最大
      initialSize: 10
      minIdle: 10
      maxActive: 200
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 180000
      testOnBorrow: false
      testWhileIdle: true
      removeAbandoned: true
      removeAbandonedTimeout: 1800
      logAbandoned: true
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxOpenPreparedStatements: 100
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

#mybatis
mybatis:
  # 实体类扫描
  type-aliases-package: com.wave.carRecord.bean.**.*
  # 配置映射文件位置
  mapper-locations: classpath:mybatis/**/*.xml

#验证码
valid:
  code: 123456

